language: ruby
sudo: false
rvm:
  - 2.5.1
  - 2.2.2
gemfile:
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.5.2.x
before_script:
  - "cd test/dummy; rake db:migrate; rake db:test:prepare; cd ../.."
notifications:
  email: false
matrix:
  allow_failures:
  - rvm: 2.5.1
